name: {{ cookiecutter.repo_name }}
dependencies:
  - flake8
  - pip
  - setuptools
  - wheel
  - pandas
  - scikit-learn
  - click
  - pytest
  - pip:
      - awscli
      - python-dotenv
      - pytest-sugar
      - pytest-cov
      - -e .
  - python>=3.6
